// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['app']['App']['CancelJob'](arg1);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function ChooseOutputDirectory() {
  return window['go']['app']['App']['ChooseOutputDirectory']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['app']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetDefaultOutputDirectory() {
  return window['go']['app']['App']['GetDefaultOutputDirectory']();
}

export function GetJob(arg1) {
  return window['go']['app']['App']['GetJob'](arg1);
}

export function OpenInputFiles() {
  return window['go']['app']['App']['OpenInputFiles']();
}

export function OpenInputFilesFromPaths(arg1) {
  return window['go']['app']['App']['OpenInputFilesFromPaths'](arg1);
}

export function OpenInputFolder() {
  return window['go']['app']['App']['OpenInputFolder']();
}

export function OpenOutputDirectory(arg1) {
  return window['go']['app']['App']['OpenOutputDirectory'](arg1);
}

export function PreviewImage(arg1, arg2) {
  return window['go']['app']['App']['PreviewImage'](arg1, arg2);
}

export function PreviewWatermark(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewWatermark'](arg1, arg2, arg3);
}

export function StartJob(arg1) {
  return window['go']['app']['App']['StartJob'](arg1);
}
