// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform} from '../models';
import {app} from '../models';
import {tools} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<platform.UpdateInfo>;

export function ChooseOutputDirectory():Promise<string>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetDefaultOutputDirectory():Promise<string>;

export function GetJob(arg1:string):Promise<app.JobStatus>;

export function OpenInputFiles():Promise<Array<app.InputFile>>;

export function OpenInputFilesFromPaths(arg1:Array<string>):Promise<Array<app.InputFile>>;

export function OpenInputFolder():Promise<Array<app.InputFile>>;

export function OpenOutputDirectory(arg1:string):Promise<void>;

export function PreviewImage(arg1:string,arg2:app.PreviewOptions):Promise<app.Preview>;

export function PreviewWatermark(arg1:string,arg2:tools.WatermarkOptions,arg3:number):Promise<app.WatermarkPreview>;

export function StartJob(arg1:tools.JobRequest):Promise<string>;
